name: backend
description: A Dart backend for the Flutter app
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  web_socket_channel: ^2.4.0

  dependencies:
    flutter:
      sdk: flutter
    firebase_core: latest_version
    firebase_database: latest_version

